mysql:
    build: images/mysql
    ports:
        - "3307:3306"
    tty: true
    hostname: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - "./tmp/mysql:/var/lib/mysql"
app:
    build: images/app
    tty: true
    hostname: app
    ports:
        - "8080:80"
    expose:
        - "80"
    links:
        - mysql
